# Generated by Django 5.2.7 on 2025-10-04 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'Forgot'), (1, 'Remembered'), (2, 'Instant')])),
                ('due_date', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.flashcard')),
            ],
        ),
    ]
