# Generated by Django 5.2.7 on 2025-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_reviewresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewresult',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reviewresult',
            unique_together={('flashcard', 'userID')},
        ),
    ]
