# Generated by Django 5.2.7 on 2025-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_initialize_cards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
