# Generated by Django 5.2.7 on 2025-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_reviewresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewresult',
            name='idempotency_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
